version: '3.8'
services:
  app:
    image: webdevops/php-nginx:8.0-alpine
    restart: unless-stopped
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=512M
      - PHP_MAX_EXECUTION_TIME=-1
    #      - XDEBUG_MODE=debug
    #      - XDEBUG_START_WITH_REQUEST=yes
    #      - XDEBUG_CLIENT_PORT=9000
    #      - XDEBUG_CLIENT_HOST=host.docker.internal
    #      - XDEBUG_MAX_NESTING_LEVEL=1000
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./app:/app:rw,cached
      - ./.env:/app/.env:ro
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_USER=${MYSQL_USER-admin}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD-rootsecret}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD-secret}
      - MYSQL_DATABASE=${MYSQL_DATABASE-mydb}
    ports:
      - '${MYSQL_EXT_PORT-3306}:3306'
    volumes:
      - ./.local_data/sql:/var/lib/mysql
